"use client";

import Link from "next/link";
import { useEffect, useRef, useState, useTransition } from "react";
import type { Candidate } from "@/lib/rate";
import { vote } from "@/app/rate/actions";
import { DiscMark } from "./disc-mark";

const PAIRS: [string, string][] = [
  ["var(--sage)", "var(--mauve)"],
  ["var(--lilac)", "var(--sage)"],
  ["var(--stone)", "var(--mauve)"],
  ["var(--cream)", "var(--sage)"],
  ["var(--grey)", "var(--mauve)"],
];

/** One AI punchline. Up, down, or take it back. The vote is optimistic and the row is written server-side. */
export function CandidateCard({ c, index = 0, canVote, highlight, showSetup }: { c: Candidate; index?: number; canVote: boolean; highlight?: boolean; showSetup?: boolean }) {
  const [mine, setMine] = useState<-1 | 0 | 1>(c.mine);
  const [up, setUp] = useState(c.up);
  const [down, setDown] = useState(c.down);
  const [pending, start] = useTransition();
  const ref = useRef<HTMLElement>(null);
  const [a, b] = PAIRS[c.generation.id % PAIRS.length];

  useEffect(() => {
    if (highlight) ref.current?.scrollIntoView({ block: "center", behavior: "smooth" });
  }, [highlight]);

  function cast(v: 1 | -1) {
    const prev = mine;
    const next: -1 | 0 | 1 = prev === v ? 0 : v;
    setMine(next);
    setUp((n) => n + (v === 1 ? (next === 1 ? 1 : prev === 1 ? -1 : 0) : prev === 1 && next === -1 ? -1 : 0));
    setDown((n) => n + (v === -1 ? (next === -1 ? 1 : prev === -1 ? -1 : 0) : prev === -1 && next === 1 ? -1 : 0));
    start(() => vote(c.id, v));
  }

  const by = c.author ? [c.author.first_name, c.author.last_name].filter(Boolean).join(" ") || "a member" : "a member";
  const score = up - down;

  return (
    <article
      ref={ref}
      style={{ "--i": Math.min(index, 8) } as React.CSSProperties}
      className={`card enter flex flex-col gap-4 p-6 ${highlight ? "stamped" : ""}`}
    >
      <header className="flex items-center justify-between gap-3">
        <DiscMark a={a} b={b} size={16} />
        <span className="tabular-nums font-jak text-[13px] font-medium text-[color:var(--ink-60)]">
          {score > 0 ? "+" : ""}
          {score}
        </span>
      </header>

      {showSetup && <p className="t-sm text-[color:var(--ink-60)]">{c.generation.setup}</p>}
      <p className="riso-ink font-jak text-[20px] font-semibold leading-[1.3] tracking-[-0.01em]">{c.punchline}</p>

      <footer className="mt-auto flex items-center justify-between gap-3 pt-2">
        <span className="t-sm flex min-w-0 items-center gap-2 text-[color:var(--ink-60)]">
          {c.author?.avatar_url ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img src={c.author.avatar_url} alt="" className="h-5 w-5 rounded-full object-cover" />
          ) : null}
          <span className="truncate">generated by {by}</span>
        </span>

        {canVote ? (
          <span className="flex items-center gap-1">
            <VoteButton on={mine === 1} disabled={pending} onClick={() => cast(1)} label={`Upvote, ${up}`}>
              ▲ <span className="tabular-nums">{up}</span>
            </VoteButton>
            <VoteButton on={mine === -1} disabled={pending} onClick={() => cast(-1)} label={`Downvote, ${down}`}>
              ▼ <span className="tabular-nums">{down}</span>
            </VoteButton>
          </span>
        ) : (
          <Link href="/login" className="btn btn-paper h-9 min-h-0 gap-3 px-3 text-[13px]">
            <span>▲ {up}</span>
            <span>▼ {down}</span>
          </Link>
        )}
      </footer>
    </article>
  );
}

function VoteButton({ on, disabled, onClick, label, children }: { on: boolean; disabled: boolean; onClick: () => void; label: string; children: React.ReactNode }) {
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled}
      aria-pressed={on}
      aria-label={label}
      className={`btn h-9 min-h-0 gap-1.5 px-3 text-[13px] ${on ? "btn-ink" : "btn-paper"}`}
    >
      {children}
    </button>
  );
}
